// <auto-generated />
using System;
using JazzGuitarTabs.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace JazzGuitarTabs.Persistance.Migrations
{
    [DbContext(typeof(DatabaseService))]
    [Migration("20180621131917_Versao0.1")]
    partial class Versao01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("JazzGuitarTabs.Domain.Artists.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Artist");
                });

            modelBuilder.Entity("JazzGuitarTabs.Domain.Tabs.Tab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Artist");

                    b.Property<string>("Author");

                    b.Property<byte[]>("File");

                    b.Property<string>("FileName");

                    b.Property<bool>("IsApproved");

                    b.Property<string>("Style")
                        .HasMaxLength(255);

                    b.Property<string>("Tags");

                    b.Property<string>("Title")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Tabs");
                });
#pragma warning restore 612, 618
        }
    }
}
